### ISSUE TITLE
Missing M5EPD Dependency

### ISSUE THREAD

**Issue by zshivers** [m5stack/M5Paper_FactoryTest#1]
Project did not compile out of the box with PlatfromIO. Needed to add library dependency for M5EPD.

**Comment by OyczE** [comment]
right ... simple copy https://github.com/m5stack/M5EPD/tree/main/src and we can go.

**Comment by zshivers** [comment]
Library dependencies in PlatformIO can be specifically called out in the `platform.ini` file so that it automatically downloads them. This should be added to the repo's `platform.ini`

**Comment by zenz** [comment]
```
lib_deps =
     m5stack/M5EPD @ ^0.1.1
```

**Comment by Gitshaoxiang** [comment]
already merged [PR](https://github.com/m5stack/M5Paper_FactoryTest/pull/4) to fix the dependency issues
