### ISSUE TITLE
filesystem lacks '/' in filenames when reading(code or sd card problem?)

### ISSUE THREAD

**Issue by CofinCup** [m5stack/M5Paper_FactoryTest#20]
The file tree in my SD card looks like this(sd card test passed): 
```
SD
|
|--tag1
|     |--tag2
|     |--1234.txt
|--123.txt
```
When trying to read files in **storage**, serial output was like this (I added the arrows):
```
[  2638][D][M5EPD_Driver.cpp:68] begin(): Init SUCCESS.
[  3265][E][esp32-hal-cpu.c:110] addApbChangeCallback(): duplicate func=0x400fd4cc arg=0x3ffbde2c
[  3423][W][sd_diskio.cpp:186] sdCommand(): token error [13] 0x33
①-------->[  3423][E][sd_diskio.cpp:621] ff_sd_status(): Check status failed
[  4353][W][sd_diskio.cpp:174] sdCommand(): no token received
[  4454][W][sd_diskio.cpp:186] sdCommand(): token error [13] 0x23 
②-------->[  4454][E][sd_diskio.cpp:621] ff_sd_status(): Check status failed
[  4458][D][GT911.cpp:35] begin(): GT911: Initialization
[  4816][W][sd_diskio.cpp:186] sdCommand(): token error [13] 0x33
③-------->[  4817][E][sd_diskio.cpp:621] ff_sd_status(): Check status failed
[  4835][D][font_render.c:63] font_cache_init(): Chace use 51104 bytes
[  4941][W][Wire.cpp:204] begin(): Bus already started in Master Mode.
[  4941][W][Wire.cpp:204] begin(): Bus already started in Master Mode.
[  4945][D][systeminit.cpp:173] SysInit_Start(): done
OK
[  5636][D][epdgui.cpp:131] EPDGUI_MainLoop(): Run Frame_Main
[  6348][D][font_render.c:63] font_cache_init(): Chace use 6820 bytes
[  8261][D][epdgui.cpp:83] EPDGUI_Run(): Exit Frame_Main
[  8262][D][epdgui.cpp:131] EPDGUI_MainLoop(): Run Frame_FileIndex
[ 14328][D][frame_fileindex.cpp:13] key_fileindex_floder_cb(): tag1
[ 14962][D][epdgui.cpp:83] EPDGUI_Run(): Exit Frame_FileIndex
[ 14962][D][epdgui.cpp:131] EPDGUI_MainLoop(): Run Frame_FileIndex
④-------->[ 14962][E][vfs_api.cpp:29] open(): tag1 does not start with /
[ 14967][D][frame_fileindex.cpp:70] listDir(): Failed to open directory
```
Here I met two problems: 
1. **test** shows SD card status was **passed**, however diskio gives "check status failed".
2. when opening _tag1_ directory, vfs gives "does not start with /". 
   1. I checked the code in _vfs_api.cpp_, it forced all filenames to be started with "/", so file wasn't permitted to be opened in the first place
   2. Then I changed the code in _vfs_api.cpp_, adding "/" for every filename that doesn't start with it. Then I succeeded in opening tag1(showing _tag2_ and _1234.txt)_, I believe this inferred that sd card can be normally accessed, plus the contents were good? **At this time, the top banner shows SDtag1, lacking '/'.**
   3. After changing the code, when opening /SD/123.txt, system still fails, giving the code below. Meanwhile, when opening /SD/tag1/tag2/ and /SD/tag1/1234.txt, serial monitor says "/sd/tag2/" and "/sd/1234.txt" doesn't exist (jumping over tag1, inferring the filepath concatnation failed). **plus, here the top banner shows SDtag2, jumping over tag1, and still lacks '/'**. 
```
[ 41005][D][epdgui.cpp:131] EPDGUI_MainLoop(): Run Frame_FileIndex
[ 43836][D][frame_fileindex.cpp:29] key_fileindex_text_cb(): 123.txt
[ 44464][D][epdgui.cpp:83] EPDGUI_Run(): Exit Frame_FileIndex
[ 44465][D][epdgui.cpp:131] EPDGUI_MainLoop(): Run Frame_txtReader
[ 45196][D][font_render.c:63] font_cache_init(): Chace use 73376 bytes
[ 45563][W][sd_diskio.cpp:186] sdCommand(): token error [13] 0x33
[ 45563][E][sd_diskio.cpp:621] ff_sd_status(): Check status failed
[ 45565][W][sd_diskio.cpp:186] sdCommand(): token error [13] 0x33
[ 45570][E][sd_diskio.cpp:621] ff_sd_status(): Check status failed
[ 49378][E][M5EPD_Driver.cpp:531] WaitBusy(): Device response timeout.
[ 49378][E][M5EPD_Driver.cpp:531] WaitBusy(): Device response timeout.
```

I know changing the library code isn't right, but I'm not clear about the factory test code structure. I was trying to find out where the bug is these days, but it seems that I lacked the ability...

**Comment by icyqwq** [comment]
Every file access must begin with a '/'. In your case, the correct path should be '/tag1/1234.txt'.
