### ISSUE TITLE
call of overloaded 'begin(int&, int&, int)' is ambiguous

### ISSUE THREAD

**Issue by wangqn** [m5stack/M5Paper_FactoryTest#9]
src/frame/frame_factorytest.cpp: In member function 'bool Frame_FactoryTest::checkGrove(int, int)':
src/frame/frame_factorytest.cpp:180:32: error: call of overloaded 'begin(int&, int&, int)' is ambiguous
     Wire1.begin(sda, scl, 10000);
                                ^
In file included from .pio/libdeps/m5stack-fire/M5EPD/src/M5EPD.h:5,
                 from src/frame/frame_base.h:4,
                 from src/frame/frame_factorytest.h:4,
                 from src/frame/frame_factorytest.cpp:1:
C:/Users/name/.platformio/packages/framework-arduinoespressif32/libraries/Wire/src/Wire.h:79:10: note: candidate: 'bool TwoWire::begin(int, int, uint32_t)'
     bool begin(int sda=-1, int scl=-1, uint32_t frequency=0); // returns true, if successful init of i2c bus
          ^~~~~
C:/Users/name/.platformio/packages/framework-arduinoespressif32/libraries/Wire/src/Wire.h:80:10: note: candidate: 'bool TwoWire::begin(uint8_t, int, int, uint32_t)'
     bool begin(uint8_t slaveAddr, int sda=-1, int scl=-1, uint32_t frequency=0);
          ^~~~~
Compiling .pio\build\m5stack-fire\lib2b7\M5EPD\base\ftgloadr.c.o
Compiling .pio\build\m5stack-fire\lib2b7\M5EPD\base\ftglyph.c.o
*** [.pio\build\m5stack-fire\src\frame\frame_factorytest.cpp.o] Error 1

**Comment by TinyuZhao** [comment]
Thank you for your proposal, we have merged to solve this problem.
